stages:
    - test
    - deploy

test:
  stage: test
  image: imaxt:latest
  tags:
    - python
  except:
    - master
  script:
    - pip install -r requirements_dev.txt
    - export MPLBACKEND="Agg"
    - python setup.py develop
    - python setup.py flake8
    - python setup.py build_sphinx -W
    - python setup.py test

deploy:
  stage: deploy
  image: imaxt:latest
  tags:
    - python
  only:
    - tags
  except:
    - branches
  script:
    - pip install -r requirements_dev.txt
    - python setup.py sdist
    - curl -X MKCOL $REPO/imaxt-image
    - curl -XPUT $REPO/imaxt-image/imaxt-image-0.2.1.tar.gz --data-binary @dist/imaxt-image-0.2.1.tar.gz


