default:
  image: docker.io/python:3.9

stages:
    - test
    - deploy

test:
  stage: test
  script:
    - pip install -r requirements_dev.txt
    - export MPLBACKEND="Agg"
    - python setup.py develop 
    - flake8 imaxt_image

deploy:
  stage: deploy
  only:
    - tags
  except:
    - branches
  script:
    - python setup.py sdist
    - curl -X MKCOL $REPO/imaxt-image
    - curl -XPUT $REPO/imaxt-image/imaxt-image-0.17.4.tar.gz --data-binary @dist/imaxt-image-0.17.4.tar.gz
  environment:
    name: Repository
    url: http://imaxt.ast.cam.ac.uk/pip/imaxt-image/


