stages:
    - test
    - deploy

test:
  stage: test
  image: imaxt:latest
  tags:
    - python
  except:
    - master
  script:
    - pip install -r requirements_dev.txt
    - export MPLBACKEND="Agg"
    - python setup.py develop
    - python setup.py flake8
    - python setup.py build_sphinx -W
    - python setup.py test

deploy:
  stage: deploy
  image: imaxt:latest
  tags:
    - python
  only:
    - master
  script:
    - pip install -r requirements_dev.txt
    - python setup.py sdist
    - curl -X MKCOL 'http://imaxt.ast.cam.ac.uk/pip/imaxt-image'
    - curl -XPUT http://imaxt.ast.cam.ac.uk/pip/imaxt-image/imaxt-image-0.1.0.tar.gz --data-binary @dist/imaxt-image-0.1.0.tar.gz
  environment:
    name: staging
    url: http://apm14.ast.cam.ac.uk/imaxt/dist


